# Generated by Django 5.1.3 on 2024-11-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('expire_at', models.DateField(verbose_name='fecha de vencimiento')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todo',
                'db_table': 'tbl_todo',
                'ordering': ['id'],
            },
        ),
    ]
